version = 1

exclude_patterns = [
  "tests/**"
]

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "isort"

[[transformers]]
name = "black"