version = 1

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "isort"

[[transformers]]
name = "black"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "ruff"

[[transformers]]
name = "autopep8"